version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
      - '8080:80'
    volumes:
      - "C:/Users/1ag3.achralla/Desktop/SI Azterketa:/usr/local/apache2/htdocs"
